/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'financial-data': FinancialDatum;
    transactions: Transaction;
    'financial-scores': FinancialScore;
    'financial-goals': FinancialGoal;
    'sub-goals': SubGoal;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'financial-data': FinancialDataSelect<false> | FinancialDataSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'financial-scores': FinancialScoresSelect<false> | FinancialScoresSelect<true>;
    'financial-goals': FinancialGoalsSelect<false> | FinancialGoalsSelect<true>;
    'sub-goals': SubGoalsSelect<false> | SubGoalsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role?: ('admin' | 'user') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financial-data".
 */
export interface FinancialDatum {
  id: string;
  user?: (string | null) | User;
  /**
   * Pemasukan bulanan
   */
  monthlyIncome: number;
  /**
   * Pengeluaran bulanan
   */
  monthlyExpenses: number;
  /**
   * Total aset yang dimiliki
   */
  totalAssets: number;
  /**
   * Total utang yang dimiliki
   */
  totalLiabilities: number;
  /**
   * Kekayaan bersih (total aset - total utang)
   */
  netWorth?: number | null;
  /**
   * Skor keuangan yang dihitung otomatis
   */
  score?: number | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  user?: (string | null) | User;
  type: 'income' | 'expense';
  category:
    | 'salary'
    | 'freelance'
    | 'investment'
    | 'bonus'
    | 'other-income'
    | 'food'
    | 'transportation'
    | 'shopping'
    | 'bills'
    | 'entertainment'
    | 'health'
    | 'education'
    | 'other-expense';
  amount: number;
  date: string;
  /**
   * Deskripsi transaksi
   */
  description?: string | null;
  /**
   * Tujuan keuangan terkait (opsional)
   */
  relatedGoal?: (string | null) | FinancialGoal;
  /**
   * Kantong/sub-tujuan terkait (opsional)
   */
  relatedSubGoal?: (string | null) | SubGoal;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financial-goals".
 */
export interface FinancialGoal {
  id: string;
  user?: (string | null) | User;
  /**
   * Nama tujuan keuangan
   */
  name: string;
  /**
   * Deskripsi tujuan keuangan
   */
  description?: string | null;
  /**
   * Jumlah target yang ingin dicapai
   */
  targetAmount: number;
  /**
   * Tanggal target pencapaian (opsional)
   */
  targetDate?: string | null;
  priority: 'low' | 'medium' | 'high';
  /**
   * Total alokasi saat ini dari semua kantong
   */
  currentTotalAllocation?: number | null;
  /**
   * Persentase kemajuan (0-100)
   */
  progress?: number | null;
  /**
   * Tabungan bulanan yang diperlukan untuk mencapai tujuan
   */
  requiredMonthlySavings?: number | null;
  /**
   * Perkiraan tanggal pencapaian berdasarkan alokasi saat ini
   */
  estimatedCompletionDate?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sub-goals".
 */
export interface SubGoal {
  id: string;
  user?: (string | null) | User;
  /**
   * Tujuan keuangan utama
   */
  goal: string | FinancialGoal;
  /**
   * Nama kantong/sub-tujuan
   */
  name: string;
  /**
   * Deskripsi kantong/sub-tujuan
   */
  description?: string | null;
  /**
   * Jumlah yang dialokasikan untuk kantong ini
   */
  allocatedAmount?: number | null;
  /**
   * Jenis aset untuk kantong ini
   */
  assetType: 'savings' | 'stocks' | 'mutual_funds' | 'gold' | 'property' | 'crypto' | 'other';
  /**
   * Catatan tambahan
   */
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financial-scores".
 */
export interface FinancialScore {
  id: string;
  user: string | User;
  score: number;
  evaluatedAt: string;
  /**
   * Rasio utang terhadap pendapatan (%)
   */
  debtToIncomeRatio?: number | null;
  /**
   * Rasio tabungan terhadap pendapatan (%)
   */
  savingsToIncomeRatio?: number | null;
  /**
   * Rasio pengeluaran terhadap pendapatan (%)
   */
  expensesToIncomeRatio?: number | null;
  /**
   * Rasio kekayaan bersih terhadap pendapatan tahunan
   */
  netWorthRatio?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'financial-data';
        value: string | FinancialDatum;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null)
    | ({
        relationTo: 'financial-scores';
        value: string | FinancialScore;
      } | null)
    | ({
        relationTo: 'financial-goals';
        value: string | FinancialGoal;
      } | null)
    | ({
        relationTo: 'sub-goals';
        value: string | SubGoal;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financial-data_select".
 */
export interface FinancialDataSelect<T extends boolean = true> {
  user?: T;
  monthlyIncome?: T;
  monthlyExpenses?: T;
  totalAssets?: T;
  totalLiabilities?: T;
  netWorth?: T;
  score?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  category?: T;
  amount?: T;
  date?: T;
  description?: T;
  relatedGoal?: T;
  relatedSubGoal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financial-scores_select".
 */
export interface FinancialScoresSelect<T extends boolean = true> {
  user?: T;
  score?: T;
  evaluatedAt?: T;
  debtToIncomeRatio?: T;
  savingsToIncomeRatio?: T;
  expensesToIncomeRatio?: T;
  netWorthRatio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "financial-goals_select".
 */
export interface FinancialGoalsSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  description?: T;
  targetAmount?: T;
  targetDate?: T;
  priority?: T;
  currentTotalAllocation?: T;
  progress?: T;
  requiredMonthlySavings?: T;
  estimatedCompletionDate?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sub-goals_select".
 */
export interface SubGoalsSelect<T extends boolean = true> {
  user?: T;
  goal?: T;
  name?: T;
  description?: T;
  allocatedAmount?: T;
  assetType?: T;
  notes?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}